### ISSUE TITLE
duplicated modules

### ISSUE THREAD

**Issue by milossramek** [isaul32/ckeditor5-math#1]
Hi,
I've tried to build the plugin today according to http://npm.taobao.org/package/ckeditor5-math#screenshots

However, the editor does not run at all, the error is
CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.

If I comment out the ckeditor5-math entries, the editor runs normally.

Could you please help me with that? 
My environment: npm 6.13.4, yarn 1.22.0, on Ubuntu 18.04

**Comment by adyssonferreira** [comment]
Do you resolved it?

**Comment by milossramek** [comment]
No, I have no idea what to do :(

**Comment by isaul32** [comment]
My old editor build https://github.com/isaul32/ckeditor5-build-classic runs okay. So it looks like CKEditor 5 API has changed after I made this plugin. I will try to solve this problem as soon as possible.

**Comment by isaul32** [comment]
I couldn't solve this by upgrading dependencies to v17.0.0. I still guess it is related to versions and how NPM resolve different versions of dependencies.
