### ISSUE TITLE
TypeScript compilation errors with CKEditor 37.1.0

### ISSUE THREAD

**Issue by zadam** [isaul32/ckeditor5-math#102]
Hi, I'm trying to upgrade to 37.1.0, but getting these errors:

```
src/ckeditor.ts:63:18 - error TS7016: Could not find a declaration file for module '@isaul32/ckeditor5-math/src/math'. '/home/[...]/[...]/node_modules/@isaul32/ckeditor5-math/src/math.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/isaul32__ckeditor5-math` if it exists or add a new declaration (.d.ts) file containing `d
eclare module '@isaul32/ckeditor5-math/src/math';`

63 import Math from '@isaul32/ckeditor5-math/src/math';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/ckeditor.ts:64:28 - error TS7016: Could not find a declaration file for module '@isaul32/ckeditor5-math/src/autoformatmath'. '/home/[...]/[...]/node_modules/@isaul32/ckeditor5-math/src/autoformatmath.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/isaul32__ckeditor5-math` if it exists or add a new declaration (.d.ts) file containing `d
eclare module '@isaul32/ckeditor5-math/src/autoformatmath';`

64 import AutoformatMath from '@isaul32/ckeditor5-math/src/autoformatmath';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Unfortunately I don't have an experience in TypeScript to solve it myself.

**Comment by tony** [comment]
Sorry for the delay @zadam!

In your [`tsconfig.json`](https://www.typescriptlang.org/tsconfig)'s, [`include`](https://www.typescriptlang.org/tsconfig#include), add a directory containing a `d.ts` extension, and add these to it:

```typescript
declare module '@isaul32/ckeditor5-math';
declare module '@isaul32/ckeditor5-math/src/math';
```

Example:

`mybuild/tsconfig.json`:

```json
{
	"extends": "ckeditor5/tsconfig.json",
	"include": [
		"src",
		"typings",
		"../../typings"
	]
}
```

Then, in `typings/types.d.ts`:

```typescript
declare module '@isaul32/ckeditor5-math';
declare module '@isaul32/ckeditor5-math/src/math';
```

Let me know how this works, if it does, I can add it to the README.

**Comment by zadam** [comment]
Thanks!

I've added these declarations:

```typescript
declare module '@isaul32/ckeditor5-math';
declare module '@isaul32/ckeditor5-math/src/math';
declare module '@isaul32/ckeditor5-math/src/autoformatmath';
```

For some reason, besides `tsconfig.json` there's also `tsconfig.types.json` in the `ckeditor5-build-balloon-block` (which I'm using as a base) and that one seems to be used during build, so the "includes" had to be updated there.

After these changes, I'm able to build with ckeditor5-math again.

**Comment by tony** [comment]
Thank you @zadam! I will add this to the `README.md`

**Comment by tony** [comment]
Before I close this for sure

@zadam If you take a look at the README now (https://github.com/isaul32/ckeditor5-math#typescript-users), do you think this suffices as a workaround until we have a permanent solution, e.g. #99?

**Comment by zadam** [comment]
LGTM

**Comment by tony** [comment]
@zadam Perfect! 

I will close this for now as resolved. If any issue comes up again in the future feel free to start a new issue and link to this one (a new issue ensures it gets noticed at the top)
