### ISSUE TITLE
Autoformat for math

### ISSUE THREAD

**Issue by zadam** [isaul32/ckeditor5-math#11]
Hi, CKEditor 5 has markdown-like [auto formatting](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) - e.g. when you start typing `###` on a new line, it will turn the line into a H3.

It might be pretty cool to have something like also for math. With this you could avoid opening 

I know this wouldn't be a quick/easy feature, but it would be interesting to at least hear what you think ...

**Comment by isaul32** [comment]
It would be useful in terms of usability. For example `\[` and `\(` could open math popup dialog. This math auto formatting maybe should be optional feature.

**Comment by funnisquares** [comment]
I think `$` would be preferable, since it is what latex and most markdown editors use. Also having `$$` create a math-block, instead of inline would be good, I think.

**Comment by isaul32** [comment]
Feature added in version 23.3.0. See https://github.com/isaul32/ckeditor5-math#autoformat-support.
