### ISSUE TITLE
Math vs. placeholder in block mode

### ISSUE THREAD

**Issue by zadam** [isaul32/ckeditor5-math#12]
Hi, when there's no other content other than math block then this happens:

![](https://user-images.githubusercontent.com/617641/97423110-0d1adc00-190f-11eb-8352-f514bc175fce.png)

I suspect the problem is that CKEditor considers math block as empty content and therefore displays also placeholder ...

**Comment by isaul32** [comment]
It's interesting how [CKEditor placeholder](https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html) works. CKEditor adds placeholder text to heading element If I add a empty heading element to editor. I didn't know that.
![image](https://user-images.githubusercontent.com/6152131/97425316-a13e7080-191a-11eb-9971-9fa45c2582a0.png)

This CSS rule should hide placeholder text.
```css
.ck-math-tex.ck-placeholder::before {
  display: none !important;
}
```
