### ISSUE TITLE
renderEquation is receiving wrongs params from package itself

### ISSUE THREAD

**Issue by fedemp** [isaul32/ckeditor5-math#125]
`renderEquation` is defined as https://github.com/isaul32/ckeditor5-math/blob/173ac0613690b8b8df31535db785d762ded82cc8/src/utils.js#L46-L48 so the 7th parameter should be a string that matches an id in the document and the 8th is an array of string for the class.

Problem is in mathediting where `renderEquation` is using the array of class as the 7th parameter.

https://github.com/isaul32/ckeditor5-math/blob/173ac0613690b8b8df31535db785d762ded82cc8/src/mathediting.js#L174

Is this expected or is it a bug? I'm currently doing the [migration to Typescript](https://github.com/isaul32/ckeditor5-math/issues/99)

**Comment by tony** [comment]
@fedemp Do we consider this done / resolved by other means?

**Comment by fedemp** [comment]
Yeah. It was fixed when migrated to TS.
