### ISSUE TITLE
How to use this in the Vue application?

### ISSUE THREAD

**Issue by weipinglee** [isaul32/ckeditor5-math#17]
I like this math plugin  for ckeditor5,but I don't know how to use it in the Vue application.
Installed this plugin according to the ckeditor5 document,show this error "ckeditor.js:5 math-tex-typesetting-missing: Missing the mathematical typesetting engine (katex) for tex".

Thanks!

**Comment by isaul32** [comment]
It sound like you are missing global katex typesetting engine. Check this link https://katex.org/docs/browser.html#loading-as-global and try add those lines into your index.html. It should work then.

**Comment by weipinglee** [comment]
It works.Thank you!

**Comment by isaul32** [comment]
👍
