### ISSUE TITLE
Math edit position problem.

### ISSUE THREAD

**Issue by DiggingLab** [isaul32/ckeditor5-math#19]
Math edit position is wrong.
(X position is minus)
That problem was occurred current edge, chrome, safari web browser.
Please check attached screen shot.
<img width="809" alt="Screen Shot 2021-01-23 at 9 02 47 PM" src="https://user-images.githubusercontent.com/20571736/105577668-65eafb00-5dbe-11eb-844d-7603cd434e41.png">

**Comment by isaul32** [comment]
I’m sorry. I don’t have currently time to look issues related to this project for a month. I hope you find some solution yourself.

**Comment by DiggingLab** [comment]
This problem is occurred current jsfiddle website.

Please check below jsfiddle website.
https://jsfiddle.net/isaul32/3wjrkLdv/

Is it ok?
I'm still problem occurred.

**Comment by DiggingLab** [comment]
> I’m sorry. I don’t have currently time to look issues related to this project for a month. I hope you find some solution yourself.

This problem is occurred current jsfiddle website.

Please check below jsfiddle website.
https://jsfiddle.net/isaul32/3wjrkLdv/

Is it ok?
I'm still problem occurred.

**Comment by DiggingLab** [comment]
> I’m sorry. I don’t have currently time to look issues related to this project for a month. I hope you find some solution yourself.

This problem is occurred current jsfiddle website.

Please check below jsfiddle website.
https://jsfiddle.net/isaul32/3wjrkLdv/

Is it ok?
I'm still problem occurred.
