### ISSUE TITLE
Pressing spacebar before a formula deletes the rest of the lile

### ISSUE THREAD

**Issue by milossramek** [isaul32/ckeditor5-math#2]
Hi,
I observe a problem  with the math module. If I place cursor just in front of a formula and press the space bar, the formula and everything after it is deleted till the end of the line

How to test:
Start any of the jffiddle.net demos
Place the cursor after the "Lorem.." text (either directly after the last dot or directly in front of the formula)
Hit the space bar. The formula and the text after the cursor vanish (both in inline and display modes)

**Comment by milossramek** [comment]
The behaviour is sometimes different: hitting the space bar leads to line break. It can be tested by adding the line
<p><strong>dvojný integrál</strong> — určitý integrál funkcie dvoch premenných&nbsp;<span class="math-tex">\(f(x, y)\)</span>&nbsp;cez rovinnú oblasť&nbsp;<span class="math-tex">\(D\)</span>:</p>
to the text (for example in the jsfiddle.net demo) and by pressing the space bar right before the formula D at the end.
In this case also Undo stops working.

**Comment by milossramek** [comment]
Something similar happens also in the case when a formula is at the end of a line. If cursor is behind the formula and one presses the space bar, the formula vanishes

**Comment by isaul32** [comment]
Hello,

This is a interesting bug. I think this happen only when use Firefox (at least it work properly in Chrome). This needs some debugging.

**Comment by ddmm-white** [comment]
Hi. I encountered the same issue. Formula disappears if whitespace is inserted right after a formula.  Also it's not possible to place cursor after a formula using mouse in Firefox (you can only move cursor using arrow keys).
![recording](https://user-images.githubusercontent.com/9927064/77998895-7c5d2d00-733a-11ea-9055-f6b7502941f5.gif)

**Comment by isaul32** [comment]
I changed editingDowncast container class from div to span (https://github.com/isaul32/ckeditor5-math/blob/master/src/mathediting.js#L128). I think this fix space before formula issue.

**Comment by isaul32** [comment]
Relates to https://github.com/ckeditor/ckeditor5/issues/6532
