### ISSUE TITLE
CKEDITOR5 V25.0.0 support?

### ISSUE THREAD

**Issue by DiggingLab** [isaul32/ckeditor5-math#21]
I was update to ckeditor5 v25.0.0.
and then math editor not working.
is it support ckeditor5 V25.0.0?
and any plan support?

**Comment by archonic** [comment]
I'm doing my update to v25 and noticed this package causes the duplicated package error. The `npm ls` for ckeditor5-math looks like this:
```
├─┬ ckeditor5-math@24.0.0
│ ├─┬ @ckeditor/ckeditor5-clipboard@24.0.0
│ │ ├── @ckeditor/ckeditor5-core@24.0.0 deduped
│ │ ├── @ckeditor/ckeditor5-engine@24.0.0 deduped
│ │ └── @ckeditor/ckeditor5-utils@24.0.0 deduped
│ ├─┬ @ckeditor/ckeditor5-core@24.0.0
│ │ ├── @ckeditor/ckeditor5-engine@24.0.0 deduped
│ │ ├── @ckeditor/ckeditor5-utils@24.0.0 deduped
│ │ └── lodash-es@4.17.20 deduped
│ ├─┬ @ckeditor/ckeditor5-engine@24.0.0
│ │ ├── @ckeditor/ckeditor5-utils@24.0.0 deduped
│ │ └── lodash-es@4.17.20 deduped
│ ├─┬ @ckeditor/ckeditor5-ui@24.0.0
│ │ ├── @ckeditor/ckeditor5-core@24.0.0 deduped
│ │ ├── @ckeditor/ckeditor5-utils@24.0.0 deduped
│ │ └── lodash-es@4.17.20 deduped
│ ├─┬ @ckeditor/ckeditor5-undo@24.0.0
│ │ ├── @ckeditor/ckeditor5-core@24.0.0 deduped
│ │ ├── @ckeditor/ckeditor5-engine@24.0.0 deduped
│ │ └── @ckeditor/ckeditor5-ui@24.0.0 deduped
│ ├─┬ @ckeditor/ckeditor5-utils@24.0.0
│ │ └── lodash-es@4.17.20 deduped
│ └─┬ @ckeditor/ckeditor5-widget@24.0.0
│   ├── @ckeditor/ckeditor5-core@24.0.0 deduped
│   ├── @ckeditor/ckeditor5-engine@24.0.0 deduped
│   ├─┬ @ckeditor/ckeditor5-typing@24.0.0
│   │ ├── @ckeditor/ckeditor5-core@24.0.0 deduped
│   │ ├── @ckeditor/ckeditor5-engine@24.0.0 deduped
│   │ ├── @ckeditor/ckeditor5-utils@24.0.0 deduped
│   │ └── lodash-es@4.17.20 deduped
│   ├── @ckeditor/ckeditor5-ui@24.0.0 deduped
│   ├── @ckeditor/ckeditor5-utils@24.0.0 deduped
│   └── lodash-es@4.17.20 deduped
```

I tried removing the explicit core and engine dependencies but still got the duplicated packages error.

**Comment by isaul32** [comment]
Math plugin must be in the same version as CKEditor 5 or vice versa. I will try update dependencies and release new version today.

**Comment by isaul32** [comment]
I failed upgrade to v25.0.0. CKEditor Modules cannot be resolved and this needs more debugging than normally. Unfortunately I don't have time to find solution for now.

**Comment by tony** [comment]
I was able to use v25.0.0 successfully when I tried.  

https://www.npmjs.com/package/@peergrade/ckeditor5-math
https://github.com/eduflow/ckeditor5-math/tree/eduflow-v25.0.0

I will PR this change

**Comment by tony** [comment]
@archonic @isaul32 

You may be using a build with different packages than me - I'm not getting the same error. 🤷 

Question:
- When these dependency issues happen, it's when creating the ckeditor5 build itself, right? (Not this repo itself)
- Have you tried `rm -rf node_modules` and `npm i` again? 
- Have you tried yarn instead?  (Interestingly, [ckeditor recommends it for troubleshooting](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html#customizing-a-build))

   ![image](https://user-images.githubusercontent.com/26336/109659101-f4c10500-7b2c-11eb-8878-cda0a5dba281.png)

I've had similar issues  and fixed them via a clean build

**Comment by isaul32** [comment]
1. Yes
2. Yes
3. I use Yarn and yarn link

I merged PR but I can’t publish plugin (no access to computer for while). Can you @tony do it if I give permission to repo and NPM?

**Comment by tony** [comment]
> I merged PR but I can’t publish new version to NPM (no access to computer for while). Can you @tony do it if I give permission to repo and NPM?

Yep. NPM user is tony (same name)

**Comment by isaul32** [comment]
> > I merged PR but I can’t publish new version to NPM (no access to computer for while). Can you @tony do it if I give permission to repo and NPM?
> 
> Yep. NPM user is tony (same name)

Thank you. Permissions are now given.

**Comment by tony** [comment]
@isaul32 

[25.0.0 published on npm](https://www.npmjs.com/package/ckeditor5-math/v/25.0.0)

On GH, when pushing the tag

```
ckeditor5-math on  master ❯ git push --tag origin v25.0.0
ERROR: Permission to isaul32/ckeditor5-math.git denied to tony.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by isaul32** [comment]
> @isaul32
> 
> [25.0.0 published on npm](https://www.npmjs.com/package/ckeditor5-math/v/25.0.0)
> 
> On GH, when pushing the tag
> 
> ```
> ckeditor5-math on  master ❯ git push --tag origin v25.0.0
> ERROR: Permission to isaul32/ckeditor5-math.git denied to tony.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

Looks like invitation is awaiting your response. Did you get invitation email?

**Comment by tony** [comment]
> Looks like invitation is awaiting your response. Did you get invitation email?

That was it. Accepted and pushed the tag: https://github.com/isaul32/ckeditor5-math/tree/v25.0.0

**Comment by DiggingLab** [comment]
I tested v25.0.0.
Well done.
Thank you!!

**Comment by tony** [comment]
@DiggingLab Excellent! Enjoy!

**Comment by tony** [comment]
Closing per #26
