### ISSUE TITLE
Custom Build duplicated modules error

### ISSUE THREAD

**Issue by lugotal** [isaul32/ckeditor5-math#22]
Hello,

I've followed the steps to install ckeditor5-math, using v24 of CKEDitor 5 and v24 of ckeditor5-math.

The build worked fine and I got it in my [forked repository](https://github.com/lugotal/ckeditor5/tree/mathbuild).
However, when installing that branch and then trying to use this custom build in my react application, I get the duplicated modules error.

Any ideas?

**Comment by isaul32** [comment]
Build looks fine. Does custom build work without math plugin and how have you imported it to react application?
