### ISSUE TITLE
Lazy loading of the rendering engine

### ISSUE THREAD

**Issue by zadam** [isaul32/ckeditor5-math#5]
Hi, first of all, thank you for this project. I'm pretty sure a lot of people have been waiting for this!

I do have a question / feature request.

This module can be configured with engine like katex, but its loading is left up to the app developer - ckeditor5-math just expects it to be there. This is not difficult to handle - app can just load katex on its own.

However, think of a use case where an app uses CKEditor and the math is used only in some specific content, so the user edits math and needs this module only from time to time. But with current approach the katex (pretty large library) must be loaded even if there's no need for it currently.

So what I propose is some sort of lazy loading mechanism where this module would detect the math usage on the page (or when user clicks on the toolbar) in the currently edited content so the module would call some (promise returning) callback which would then lazy load Katex.

What do you think?

**Comment by isaul32** [comment]
Thanks very much. Could you use a custom typesetting config for that? Look [custom typesetting](https://github.com/isaul32/ckeditor5-math#available-typesetting-engines) and this [example](https://github.com/isaul32/ckeditor5-math-examples/blob/master/jlatexmath-example/frontend/src/index.js#L6-L38). Or did you mean some sort built-in autoload feature which can turned on by config?

**Comment by zadam** [comment]
Yes, I was thinking that custom engine function could be in theory used for that, however:

*   in the function I can lazy load the katex, but then need to also call it to render the equation so I need to develop custom code to integrate with katex which seems sort of unnecessary when this logic is already implemented in ckeditor5-math, just not accessible in the engine function.
*   I assume this engine function is called asynchronously for each equation in the document, this could lead to multiple attempts to lazy load / initialize the engine library.

Of course both of these are solveable, but my impression is that lazy loading is such generally useful functionality that it would deserve specific support.

The way I imagine it, the config would stay the same, just with the addition of one config option:

```
math: {
	engine: 'katex', 
	lazyLoad: async () => {
		// return the promise which resolves upon loading the library
	}
	... // other settings
}
```

Now `ckeditor5-math` goes through the document and looks for the equations and for each of them calls either katex, mathjax or engine function.

Now the logic would have to be modified - it still looks for the equations, if the engine is configured as katex or mathjax, it checks if these are available, if not, it will call `lazyLoad` config function and wait until the returned promise resolves, then continues with the flow as usual.

**Comment by isaul32** [comment]
I implemented the first version of this feature: https://github.com/isaul32/ckeditor5-math/pull/6

So, lazyLoad is called once before rendering first equation if engine isn't loaded. After resolving promise, plugin renders all pending equations.

What do you think about it and does it fulfill your request?

**Comment by zadam** [comment]
Yes, this looks like exactly what I had in mind, thanks!

**Comment by isaul32** [comment]
New v23.1.0 release with this feature is now available in NPM. I leave this pull request open for while if it still needs some fix.
