### ISSUE TITLE
Not working in vue.js

### ISSUE THREAD

**Issue by nicolas15000** [isaul32/ckeditor5-math#50]
**My package.json :** 
```
"@ckeditor/ckeditor5-build-classic": "^24.0.0",
"ckeditor5-math": "^24.0.0"
```

**My vue.js file :** 
```

import CKEditor from '@ckeditor/ckeditor5-vue2';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import Mathematics from 'ckeditor5-math/src/math';

  data() {
        return {
            editor: ClassicEditor,
            editorData: '<p>Content of the editor.</p>',
            editorConfig: {
                // The configuration of the editor.
                     toolbar: [items: [
                          'math'
		     ] ],
                    plugins: [ Mathematics]
            }
        };
    }
```

**the Error :** 

`Uncaught (in promise) CKEditorError: ckeditor-duplicated-modules`

I have modified both versions , with no luck

**Comment by isaul32** [comment]
You need build CKEditor with math plugin. See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html and https://github.com/isaul32/ckeditor5-math#installation.

**Comment by thanhttb** [comment]
> You need build CKEditor with math plugin. See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html and https://github.com/isaul32/ckeditor5-math#installation.

I followed the instruction but after rebuild, I still got this error 
`CKEditorError: ckeditor-duplicated-modules` 
when open the original sample file of CKEditor.
<img width="1286" alt="Screen Shot 2021-11-09 at 23 44 33" src="https://user-images.githubusercontent.com/22235844/140967257-f0e2fc3c-215a-4756-99fe-315ec4683694.png">
