### ISSUE TITLE
Duplicate packages when installed into CKEditor v31

### ISSUE THREAD

**Issue by archonic** [isaul32/ckeditor5-math#53]
Looks like v31 introduces a duplicate packages issue. I haven't looked into which packages those are yet but figured I'd open the issue while I remember to do so.

**Comment by loading99** [comment]
I got the same problem with version v30.0.0.

**Comment by fauguste** [comment]
I've got the same too on  v30.0.0.

**Comment by tony** [comment]
It needs a 30.0.0 release, on it.

**Comment by tony** [comment]
@archonic @loading99 @fauguste @rogatty If you try the new releases for 31.0.0 and 31.1.0, do those work?

Let me know

**Comment by fauguste** [comment]
@tony it's ok for on release 31.1.0.

**Comment by tony** [comment]
@fauguste Excellent!

@archonic I will give some more time to until I close this (I don't want to do it too soon). If you find it works on your side please feel free to close

If anything else comes up please feel free to chime in, bit it here (if still open) or a new issue.

**Comment by archonic** [comment]
Thanks @tony! I'll give this a go soon, just have to get other stuff out the door first.

**Comment by rogatty** [comment]
Works as expected with v31.1.0 👍  Thanks @tony!

**Comment by tony** [comment]
@rogatty Excellent!

**Comment by tony** [comment]
Closing this per the release of v31.0.0 and v31.1.0

If this persists please create a new issue and cite this if needed
