### ISSUE TITLE
Question: Use with Custom-Build CKEditor5

### ISSUE THREAD

**Issue by topse** [isaul32/ckeditor5-math#60]
Hi,
I am sorry to bother...  I want to use a custom build of CKEditor5 with this brilliant plugin in a Next-JS environment:

```
  return (
    <div>
      {isLayoutReady ? (
        <>
          <Script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js" id="MathJax-script" async/>
          <CKEditor editor={ClassicEditor} data={getValues(fieldName)} />
        </>
      ) : null}
    </div>
  );
```

This works very well... The only problem is: I want MathJax to be loaded locally from "node_modules/mathjax/es5/tex-svg.js"... I really don't get, what to do... Can someone give me a hint?

Best Regards,
           Tobias

**Comment by exniwe** [comment]
Can you show more of your solution? I am trying to do the same, but I get the following error when I try what you have described

Refused to execute script from `'my-path/mathjax/es5/tex-svg.js'` because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by topse** [comment]
Sorry... I switched the project away from next.js and dont have the "old stuff" anymore...

Best Regards,
Tobias
