### ISSUE TITLE
Duplicate packages when installed into CKEditor v35.1

### ISSUE THREAD

**Issue by zgpnuaa** [isaul32/ckeditor5-math#65]
v35.1 also introduces a duplicate packages issue. 
![image](https://user-images.githubusercontent.com/38033949/188295591-db43b764-0f24-4baf-9d6b-b2dc55d46be6.png)

**Comment by eorhan** [comment]
+1

**Comment by zgpnuaa** [comment]
> +1 ![Ekran Resmi 2022-09-07 01 40 29](https://user-images.githubusercontent.com/15705526/188752882-48333a35-03c8-433a-9359-4bc68e0052ba.png)

when i delete dirs and files of "ckeditor5-math/node_modules" , and then npm run build, it works.

**Comment by tony** [comment]
@zgpnuaa @eorhan If you try [v35.1.0](https://www.npmjs.com/package/ckeditor5-math/v/35.1.0) on NPM, is it any better?

**Comment by zgpnuaa** [comment]
> @zgpnuaa @eorhan如果你在 NPM 上尝试[v35.1.0](https://www.npmjs.com/package/ckeditor5-math/v/35.1.0)会更好吗？

In github, it's 35.1.0, but in npm, it's 34.2.0.
So not working, same error "Duplicate packages ".

**Comment by tony** [comment]
@zgpnuaa 

Are you saying [35.1.0](https://www.npmjs.com/package/ckeditor5-math/v/35.1.0) on NPM's package.json is pointing to 34.2.0?

**Comment by tony** [comment]
Can you use the same ckeditor5-math version as the ckeditor you're running, then try?

(You may need to wipe your lockfile and node_modules before rebuilding)

The reason this happens in [`ckeditor-duplicated-modules`](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules)

**Comment by tony** [comment]
I will close this for now as resolved, please let me know if anything else comes up!

I've also published 35.2.0 and 35.2.1 to NPM if you update CKEditor further
