### ISSUE TITLE
Accessibility of edit button in balloon editor

### ISSUE THREAD

**Issue by zadam** [isaul32/ckeditor5-math#7]
Hello, I use "balloon" editor in my app instead of the classic toolbar.

There's a problem that if I choose alternative display style (block style instead of inline), then I can't re-edit the math formula.

You can see the problem on this clip:

![](https://user-images.githubusercontent.com/617641/96190502-a2e35e00-0f42-11eb-8a3a-8501a53eaedf.gif)

Also it seems a little bit unintuitive that I need to click on the f(x) button to be able to edit the formula. Wouldn't simple click (or perhaps double click) on the rendered formula be better way to show the edit dialog?

Compare with how this works in ckeditor for normal links (click triggers dialog):

![](https://user-images.githubusercontent.com/617641/96190941-6401d800-0f43-11eb-8630-1bb9cfe952a3.gif)

**Comment by isaul32** [comment]
Feature added to v23.2.0.

**Comment by zadam** [comment]
Awesome, thanks!
