### ISSUE TITLE
Make a Build

### ISSUE THREAD

**Issue by milad2golnia** [isaul32/ckeditor5-math#85]
In many cases we need dll builds to add plugins. As mentioned in [official website](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds.html). Also having a dll build, we can use it in [different packages](https://github.com/nshenderov/strapi-plugin-ckeditor/issues/71#issue-1576419263).

Would you please provide a dll build of this plugin? Or guide me how I can build one?

**Comment by tony** [comment]
Hi! I am currently cleaning up issues.

Builds can be found at [`@isaul32/ckeditor5-math`](https://www.npmjs.com/package/@isaul32/ckeditor5-math). Newer versions now use DLL builds.
