### ISSUE TITLE
Build as an independent plugin

### ISSUE THREAD

**Issue by milossramek** [isaul32/ckeditor5-math#9]
Hi, 
I've managed to build a complete editor including ckeditor5-math according to the provided instructions.

Is it possible to build ckeditor5-math as an independent plugin, to use it then with ckeditor5 from its CDN or with a prebuilt one from the online builder at https://ckeditor.com/ckeditor-5/online-builder/?

Thanks!

**Comment by isaul32** [comment]
Hi,

I'm sorry but I don’t think it’s possible. Take a look at https://github.com/ckeditor/ckeditor5/issues/1047#issuecomment-393068327 and https://github.com/ckeditor/ckeditor5/issues/667.

**Comment by milossramek** [comment]
Thank you for the explanation!
An obvious solution would be to include your plugin in the list of officially supported plugins, so that one can use it directly from the CDN.

Do you think it is possible? Can I vote for your plugin somewhere? :-)?

**Comment by isaul32** [comment]
I can't do that. It's up to CKSource team. Their official math plugin is MathType by their partner Wiris. I don't think they want to offer officially other alternatives. You can give a star on GitHub if you want support this plugin :smile:.
