### ISSUE TITLE
NPM access

### ISSUE THREAD

**Issue by tony** [isaul32/ckeditor5-math#92]
@isaul32 Can I have publish access for https://www.npmjs.com/package/@isaul32/ckeditor5-math to publish [v36.0.5](https://github.com/isaul32/ckeditor5-math/blob/v36.0.5/CHANGELOG.md)?

**Comment by tony** [comment]
@isaul32 Hi, can you take a look at this please? 🙏

**Comment by tony** [comment]
@isaul32 Thank you! 🙏

**Comment by isaul32** [comment]
I had already invited you. I've now invited you again.

**Comment by tony** [comment]
Thank you

**Comment by tony** [comment]
@isaul32 In hindsight, yes it's true. You invited me on March 14th but I didn't click the invite link. I didn't remember I needed to
